#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn build:check
yarn workspace @slangy/common lint-staged
yarn workspace @slangy/server lint-staged
yarn workspace @slangy/client lint-staged
yarn workspace @slangy/mongo lint-staged
